#!/bin/bash

FILENAME="default.py"
IP_ADDRESS="192.168.1.2" # On Netgear router
USER="mikael"
REMOTE_PATH="$USER@$IP_ADDRESS:/home/$USER/sml_summerproject/myapp/"
LOCAL_PATH="/home/nvidia/sml_summerproject/myapp"
PASSWORD_PATH="/home/nvidia/sml_summerproject/password/password.txt"

echo Starting run car script
echo Copying code file from "$REMOTE_PATH$FILENAME"

sshpass -f $PASSWORD_PATH scp "$REMOTE_PATH$FILENAME" $LOCAL_PATH
echo code has been copied

echo Starting zed_SVEA_high_level_commands
roslaunch svea zed_SVEA_high_level_commands.launch my_args:="$FILENAME"
